# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo I am provisioning...

wget http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
apt-key add rabbitmq-signing-key-public.asc

add-apt-repository "deb http://www.rabbitmq.com/debian/ testing main"
apt-get update --fix-missing

apt-get install -q -y cowsay mono-complete rabbitmq-server

echo "Ready to go!\n\nNode: $(node -v)" | /usr/games/cowsay

SCRIPT


VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :forwarded_port, guest: 4000, host: 4001
  config.vm.provision :shell, inline: $script
end